### PR TITLE
Add AocodaF4v3 target

### PR DESCRIPTION
**Pull request by 634296207**
1. Use the User1 and User2 modes
2. Serial port 5 Use Bluetooth
3. Serial port 2 Use a receiver
4. Serial port 3 Use power callback
5. Serial port 1 Use GPS
6. Bluetooth and 9v switches are enabled by default

### CODE REVIEW

**Comment by 634296207** [comment]
1. Use the User1 and User2 modes
2. Serial port 5 Use Bluetooth
3. Serial port 2 Use a receiver
4. Serial port 3 Use power callback
5. Serial port 1 Use GPS
6.Bluetooth and 9v switches are enabled by default

**Comment by lida2003** [comment]
Is this a new PR for adding AOCODARCF4V3 target https://github.com/Aocoda-RC/inav/pull/1

图片


1) As I have no idea about the title " Create CMakeLists #3 "
2) BTW, you can move descriotion just below the title>

> * Use the User1 and User2 modes
> 
> * Serial port 5 Use Bluetooth
> 
> * Serial port 2 Use a receiver
> 
> * Serial port 3 Use power callback
> 
> * Serial port 1 Use GPS
> 
> * Bluetooth and 9v switches are enabled by default

**Comment by 634296207** [comment]
F405V3 Flash V2(HW) self test passed.

**Comment by 634296207** [comment]
1.Add the sd card or FLash select compilation function
2.Add SPL06
3.Camera control function

**Pull request merged**
